(() => {
  state.runLevels = {...{quality:0,steady:0,long:0}, ...(state.runLevels || {})};
  const level = t => Math.max(0,Math.min(11,state.runLevels[t] || 0));
  const target = w => plan().find(x=>x.type==='run'&&x.template===w.template&&x.week===level(w.template)+1) || w;
  function apply(w,log){const old=level(w.template),pain=+log.knee||0,rpe=+log.rpe||6;let success=false,reason='';if(pain>=4){reason='Pain was elevated, so progression is paused.'}else if(w.template==='quality'){success=(+log.intervalsCompleted>=+log.intervalsTarget)&&rpe<=8;reason=success?'All intervals completed at controlled effort.':'Repeat this level until all intervals are completed at controlled effort.'}else{success=(+log.distance>=+log.targetDistance*.98)&&rpe<=7;reason=success?'Target distance completed at controlled effort.':'Repeat this level until the target distance feels controlled.'}if(success&&old<11)state.runLevels[w.template]=old+1;else if(pain>=5&&old>0)state.runLevels[w.template]=old-1;log.runProgression={fromLevel:old+1,toLevel:level(w.template)+1,progressed:success,reason};return log.runProgression}
  window.adaptiveRunLevel=level;window.adaptiveRunTarget=target;window.applyRunProgression=apply;
  const base=openWorkout;
  openWorkout=function(i){const scheduled=plan()[i];if(scheduled.type!=='run')return base(i);const w=target(scheduled),existing=state.logs[scheduled.id]||{},quality=scheduled.template==='quality';const rounds=quality?[4,4,5,4,4,5,4,4,5,4,4,3][w.week-1]:0;workoutDialog.innerHTML=`<div class="sheet-content"><div class="between row"><div><p class="eyebrow">RUN LEVEL ${level(scheduled.template)+1}</p><h2>${scheduled.title}</h2></div><button class="icon-button" onclick="workoutDialog.close()">×</button></div><section class="session-instructions">${window.sessionDetails?window.sessionDetails(w):''}</section><div class="grid-2"><div class="field"><label>Distance (km)</label><input id="distance" type="number" step="0.01" value="${existing.distance||w.distance||''}"></div><div class="field"><label>Time (minutes)</label><input id="duration" type="number" step="0.1" value="${existing.duration||w.minutes}"></div></div>${quality?`<div class="grid-2"><div class="field"><label>Intervals completed</label><input id="intervalsCompleted" type="number" min="0" max="${rounds}" value="${existing.intervalsCompleted??rounds}"></div><div class="field"><label>Intervals prescribed</label><input id="intervalsTarget" type="number" value="${rounds}" readonly></div></div>`:''}<div class="field"><label>Average heart rate (optional)</label><input id="avgHeartRate" type="number" placeholder="e.g. 146" value="${existing.avgHeartRate||''}"></div><div class="field"><label>Knee pain 0-10</label><input id="knee" type="range" min="0" max="10" value="${existing.knee||0}"></div><div class="field"><label>Effort 1-10</label><input id="rpe" type="range" min="1" max="10" value="${existing.rpe||6}"></div><button class="primary" id="adaptiveComplete">Complete workout</button></div>`;adaptiveComplete.onclick=()=>{const log={id:scheduled.id,type:'run',template:scheduled.template,completed:true,date:new Date().toISOString(),duration:+duration.value||w.minutes,distance:+distance.value||0,knee:+knee.value,rpe:+rpe.value,avgHeartRate:+avgHeartRate.value||null,targetDistance:+w.distance||0};if(quality){log.intervalsCompleted=+intervalsCompleted.value||0;log.intervalsTarget=+intervalsTarget.value||rounds}apply(scheduled,log);state.logs[scheduled.id]=log;save();workoutDialog.close();render('today')};workoutDialog.showModal()};
})();
