const STORAGE='hybrid-training-v1';
const startDefault='2026-08-10';
const exercises={
 push:[['Bench press',4,6,8,80,2.5],['Incline dumbbell press',3,8,10,24,2],['Shoulder press',3,8,10,35,2.5],['Lateral raise',3,12,15,8,1],['Triceps pressdown',3,10,12,25,2.5]],
 pull:[['Pull-ups',4,5,8,0,2.5],['Barbell row',4,6,8,60,2.5],['Lat pulldown',3,8,10,55,2.5],['Face pull',3,12,15,25,2.5],['Hanging knee raise',3,10,15,0,0]],
 legs:[['Back squat',4,6,8,70,2.5],['Romanian deadlift',3,8,10,70,2.5],['Bulgarian split squat',3,8,10,16,2],['Leg curl',3,10,12,35,2.5],['Calf raise',3,12,15,50,5]]
};
const weeks=[
 [35,35,5,7],[35,38,5,8],[38,40,6,9],[35,35,5,8],[40,42,6,10],[42,45,7,11],[35,38,6,9],[45,45,7,13],[45,48,8,15],[40,42,7,12],[48,50,8,17],[35,35,6,18]
];
function plan(){const days=[];for(let w=0;w<12;w++){const [quality,steady,steadyKm,longKm]=weeks[w];const defs=[
 ['Push strength','strength','push',55],['Quality run','run','quality',quality],['Pull + core','strength','pull',55],['Steady run','run','steady',steady],['Leg strength','strength','legs',55],['Long run','run','long',Math.max(50,longKm*7)],['Recovery walk + mobility','recovery','recovery',40]
 ];defs.forEach((d,i)=>days.push({id:`w${w+1}d${i+1}`,week:w+1,day:i+1,title:d[0],type:d[1],template:d[2],minutes:d[3],distance:d[2]==='steady'?steadyKm:d[2]==='long'?longKm:null,hyrox:w>=2&&i===4}));}return days;}
const state=load();
function load(){const base={startDate:startDefault,logs:{},exerciseState:{},weight:87,theme:'dark'};try{return {...base,...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return base}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function dateFor(index){const d=new Date(state.startDate+'T12:00:00');d.setDate(d.getDate()+index);return d}
function dayIndex(){return Math.max(0,Math.min(83,Math.floor((new Date()-new Date(state.startDate+'T00:00:00'))/86400000)))}
function fmtDate(d){return d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}
function workout(i){return plan()[i]}
function completedCount(){return Object.values(state.logs).filter(x=>x.completed).length}
function currentWeek(){return Math.floor(dayIndex()/7)+1}
function lastExercise(name,def){return state.exerciseState[name]||{weight:def[4],target:def[2],step:def[5],lastReps:[]}}
function nextPrescription(name,def){const x=lastExercise(name,def);return {weight:x.weight,target:x.target}}
function render(view='today'){
 document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 const root=document.getElementById('view');
 if(view==='today')root.innerHTML=todayView();
 if(view==='week')root.innerHTML=weekView();
 if(view==='progress')root.innerHTML=progressView();
 if(view==='settings')root.innerHTML=settingsView();
 bind(view);
}
function todayView(){const i=dayIndex(),w=workout(i),log=state.logs[w.id]||{},pct=Math.round(completedCount()/84*100);return `<section class="card hero"><p class="eyebrow">WEEK ${w.week} OF 12</p><h2>${w.title}</h2><p class="muted">${w.minutes} min${w.distance?` · ${w.distance} km target`:''}</p><div class="progress"><span style="width:${pct}%"></span></div><p class="muted">${pct}% plan complete</p>${w.hyrox?'<div class="notice">Optional: replace today with a Hyrox session.</div>':''}<button class="primary" data-start="${i}">${log.completed?'Review workout':'Start workout'}</button></section><section class="grid-2"><div class="metric"><span class="muted">Current weight</span><strong>${state.weight} kg</strong></div><div class="metric"><span class="muted">Completed</span><strong>${completedCount()}/84</strong></div></section><section class="card"><div class="between row"><div><p class="eyebrow">TOMORROW</p><h3>${workout(Math.min(83,i+1)).title}</h3></div><span class="tag">${workout(Math.min(83,i+1)).minutes} min</span></div></section>`}
function weekView(){const wk=currentWeek(),start=(wk-1)*7;return plan().slice(start,start+7).map((w,j)=>{const done=state.logs[w.id]?.completed;return `<button class="card day-card ${done?'done':''}" data-start="${start+j}"><span class="day-badge">${done?'✓':j+1}</span><span style="text-align:left"><strong>${w.title}</strong><small class="muted" style="display:block">${fmtDate(dateFor(start+j))}</small></span><span class="tag">${w.minutes}m</span></button>`}).join('')}
function progressView(){const logs=Object.values(state.logs),runs=logs.filter(x=>x.type==='run'&&x.completed),km=runs.reduce((s,x)=>s+(+x.distance||0),0),longest=Math.max(0,...runs.map(x=>+x.distance||0));const vals=Array.from({length:12},(_,w)=>plan().slice(w*7,w*7+7).filter(x=>state.logs[x.id]?.completed).length);return `<section class="grid-2"><div class="metric"><span class="muted">Total run</span><strong>${km.toFixed(1)} km</strong></div><div class="metric"><span class="muted">Longest</span><strong>${longest.toFixed(1)} km</strong></div><div class="metric"><span class="muted">Workouts</span><strong>${completedCount()}</strong></div><div class="metric"><span class="muted">Weight</span><strong>${state.weight} kg</strong></div></section><section class="card"><h3>Weekly completion</h3><div class="chart">${vals.map((v,i)=>`<div class="bar" style="height:${Math.max(5,v/7*100)}%"><span>${i+1}</span></div>`).join('')}</div></section><section class="card"><h3>Automatic progression</h3><p class="muted">Complete every prescribed set at the top of the rep range and the next session increases automatically. Miss the target and the load repeats.</p></section>`}
function settingsView(){return `<section class="card stack"><div class="field"><label>Plan start date</label><input id="startDate" type="date" value="${state.startDate}"></div><div class="field"><label>Current weight (kg)</label><input id="bodyWeight" type="number" step="0.1" value="${state.weight}"></div><button class="secondary" id="exportBtn">Export backup</button><button class="secondary" id="importBtn">Import backup</button><button class="ghost" id="resetBtn">Reset all data</button></section><section class="card"><h3>Storage</h3><p class="muted">Your data stays on this device. Export a backup occasionally, especially before changing phones or clearing Safari data.</p></section>`}
function bind(view){document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>openWorkout(+b.dataset.start));if(view==='settings'){startDate.onchange=e=>{state.startDate=e.target.value;save();render('today')};bodyWeight.onchange=e=>{state.weight=+e.target.value;save()};exportBtn.onclick=exportData;importBtn.onclick=()=>importInput.click();resetBtn.onclick=()=>{if(confirm('Delete all training data?')){localStorage.removeItem(STORAGE);location.reload()}}}}
function openWorkout(i){const w=workout(i),existing=state.logs[w.id]||{};let body='';if(w.type==='strength'){body=exercises[w.template].map(def=>exerciseCard(def,existing.exercises?.[def[0]])).join('')}else if(w.type==='run'){body=`<div class="grid-2"><div class="field"><label>Distance (km)</label><input id="distance" type="number" step="0.1" value="${existing.distance||w.distance||''}"></div><div class="field"><label>Time (minutes)</label><input id="duration" type="number" step="0.1" value="${existing.duration||w.minutes}"></div></div><div class="field"><label>Knee pain 0-10</label><input id="knee" type="range" min="0" max="10" value="${existing.knee||0}"></div><div class="field"><label>Effort 1-10</label><input id="rpe" type="range" min="1" max="10" value="${existing.rpe||6}"></div>`}else{body=`<div class="notice">Keep this genuinely easy: walk, cycle or mobility for at least 30 minutes.</div><div class="field"><label>Minutes completed</label><input id="duration" type="number" value="${existing.duration||40}"></div>`}
 workoutDialog.innerHTML=`<form method="dialog" class="sheet-content" id="workoutForm"><div class="between row"><div><p class="eyebrow">${fmtDate(dateFor(i)).toUpperCase()}</p><h2>${w.title}</h2></div><button class="icon-button" value="cancel">×</button></div>${body}<div class="field"><label>Notes</label><textarea id="notes" rows="3">${existing.notes||''}</textarea></div><button type="button" class="primary" id="completeBtn">${existing.completed?'Save changes':'Complete workout'}</button></form>`;
 completeBtn.onclick=()=>completeWorkout(i,w);workoutDialog.showModal();
}
function exerciseCard(def,saved){const [name,sets,min,max]=def,p=nextPrescription(name,def),reps=saved?.reps||Array(sets).fill(p.target);return `<div class="exercise" data-exercise="${name}"><div class="between row"><div><h3>${name}</h3><small class="muted">Goal ${sets} × ${p.target}</small></div><span class="tag">${p.weight?p.weight+' kg':'Bodyweight'}</span></div>${Array.from({length:sets},(_,i)=>`<div class="set-row"><strong>${i+1}</strong><input class="set-weight" type="number" step="0.5" value="${saved?.weights?.[i]??p.weight}" aria-label="Weight"><input class="set-reps" type="number" value="${reps[i]??p.target}" aria-label="Reps"><button type="button" class="set-check ${saved?.done?.[i]?'checked':''}" onclick="this.classList.toggle('checked')">✓</button></div>`).join('')}</div>`}
function completeWorkout(i,w){const log={id:w.id,type:w.type,completed:true,date:new Date().toISOString(),notes:notes.value};if(w.type==='strength'){log.exercises={};document.querySelectorAll('[data-exercise]').forEach(card=>{const name=card.dataset.exercise,weights=[...card.querySelectorAll('.set-weight')].map(x=>+x.value),reps=[...card.querySelectorAll('.set-reps')].map(x=>+x.value),done=[...card.querySelectorAll('.set-check')].map(x=>x.classList.contains('checked'));log.exercises[name]={weights,reps,done};const def=exercises[w.template].find(x=>x[0]===name),prev=lastExercise(name,def),all=done.every(Boolean)&&reps.every(r=>r>=def[3]);state.exerciseState[name]={weight:all?(weights[0]||prev.weight)+def[5]:(weights[0]||prev.weight),target:def[3],step:def[5],lastReps:reps};});}else{log.duration=+duration.value||w.minutes;if(w.type==='run'){log.distance=+distance.value||0;log.knee=+knee.value;log.rpe=+rpe.value;if(log.knee>=5)log.warning='Knee pain was high. Replace the next quality run with easy cycling.';}}state.logs[w.id]=log;save();workoutDialog.close();render('today')}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='hybrid-training-backup.json';a.click();URL.revokeObjectURL(a.href)}
importInput.onchange=e=>{const r=new FileReader();r.onload=()=>{try{Object.assign(state,JSON.parse(r.result));save();location.reload()}catch{alert('Invalid backup file')}};r.readAsText(e.target.files[0])};
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>render(b.dataset.view));themeToggle.onclick=()=>{document.documentElement.classList.toggle('light');state.theme=document.documentElement.classList.contains('light')?'light':'dark';save()};if(state.theme==='light')document.documentElement.classList.add('light');document.getElementById('todayLabel').textContent=fmtDate(new Date()).toUpperCase();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
