(() => {
  const META_KEY='hybrid-training-backup-meta-v1';
  const ALLOWED=['startDate','weight','theme','logs','prescriptions','history','runLevels'];
  const meta=()=>{try{return JSON.parse(localStorage.getItem(META_KEY)||'{}')}catch{return {}}};
  const completed=()=>Object.values(state.logs||{}).filter(x=>x?.completed).length;
  const backupPayload=()=>{const data={};ALLOWED.forEach(k=>{if(state[k]!==undefined)data[k]=state[k]});return {format:'hybrid-training-backup',version:2,createdAt:new Date().toISOString(),data}};
  const validObject=v=>v&&typeof v==='object'&&!Array.isArray(v);
  function validate(payload){if(!validObject(payload)||payload.format!=='hybrid-training-backup'||!validObject(payload.data))throw new Error('Not a Hybrid Training backup.');const d=payload.data;if(typeof d.startDate!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(d.startDate))throw new Error('Backup start date is invalid.');if(typeof d.weight!=='number'||!Number.isFinite(d.weight))throw new Error('Backup body weight is invalid.');if(typeof d.theme!=='string')throw new Error('Backup theme is invalid.');['logs','prescriptions','history'].forEach(k=>{if(!validObject(d[k]))throw new Error(`Backup ${k} is invalid.`)});if(d.runLevels!==undefined&&!validObject(d.runLevels))throw new Error('Backup running progression is invalid.');return d}
  function markBackedUp(payload){localStorage.setItem(META_KEY,JSON.stringify({lastBackupAt:payload.createdAt,completedAtBackup:completed()}))}
  async function copyText(text){if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(text);return true}catch{}}const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.focus();area.select();area.setSelectionRange(0,text.length);let ok=false;try{ok=document.execCommand('copy')}catch{}area.remove();return ok}
  async function copyBackup(){const payload=backupPayload();const ok=await copyText(JSON.stringify(payload));if(ok){markBackedUp(payload);alert('Backup copied to clipboard. Paste it into an iCloud Note or another safe place.');render('settings')}else showBackup(payload,'Automatic copy was blocked by iOS. Use the visible backup text below.')}
  async function exportBackup(){const payload=backupPayload(),text=JSON.stringify(payload,null,2),name=`hybrid-training-backup-${payload.createdAt.slice(0,10)}.json`,file=new File([text],name,{type:'application/json'});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({files:[file],title:'Hybrid Training backup'});markBackedUp(payload);render('settings');return}}catch(err){if(err?.name==='AbortError')return}try{const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);markBackedUp(payload);alert('Backup export started. If iOS did not offer a file/share action, use Copy backup instead.');render('settings')}catch{showBackup(payload,'File export is unavailable here. Use the visible backup text below.') }}
  function showBackup(payload=backupPayload(),message='This text is the emergency fallback backup.'){const text=JSON.stringify(payload);workoutDialog.innerHTML=`<div class="sheet-content"><div class="between row"><div><p class="eyebrow">BACKUP FALLBACK</p><h2>Your backup data</h2></div><button class="icon-button" id="closeBackup">×</button></div><div class="notice">${message}</div><textarea id="backupText" readonly style="width:100%;min-height:260px;font-size:12px;line-height:1.35;word-break:break-all"></textarea><button class="primary" id="retryCopy">Copy this backup</button><button class="secondary" id="selectBackup">Select all manually</button><button class="secondary" id="backupSaved">I saved this backup</button></div>`;workoutDialog.showModal();const close=document.getElementById('closeBackup'),box=document.getElementById('backupText'),retry=document.getElementById('retryCopy'),select=document.getElementById('selectBackup'),saved=document.getElementById('backupSaved');box.value=text;close.onclick=()=>workoutDialog.close();retry.onclick=async()=>{if(await copyText(text)){markBackedUp(payload);alert('Backup copied to clipboard.');workoutDialog.close();render('settings')}else alert('iOS blocked automatic copy. Use Select all manually.')};select.onclick=()=>{box.focus();box.setSelectionRange(0,box.value.length)};saved.onclick=()=>{markBackedUp(payload);workoutDialog.close();render('settings')}}
  function restoreData(data){const count=Object.values(data.logs||{}).filter(x=>x?.completed).length;if(!confirm(`Restore this backup?\n\nIt contains ${count} completed workouts.\n\nYour current app data will be replaced.`))return;ALLOWED.forEach(k=>delete state[k]);Object.assign(state,data);save();localStorage.setItem(META_KEY,JSON.stringify({lastBackupAt:new Date().toISOString(),completedAtBackup:count}));location.reload()}
  function showRestore(){workoutDialog.innerHTML=`<div class="sheet-content"><div class="between row"><div><p class="eyebrow">RESTORE</p><h2>Paste backup</h2></div><button class="icon-button" id="closeRestore">×</button></div><p class="muted">Paste the complete backup text from your saved copy.</p><textarea id="restoreText" style="width:100%;min-height:220px;font-size:12px" placeholder="Paste backup JSON here"></textarea><button class="primary" id="restoreNow">Validate and restore</button></div>`;workoutDialog.showModal();document.getElementById('closeRestore').onclick=()=>workoutDialog.close();document.getElementById('restoreNow').onclick=()=>{try{restoreData(validate(JSON.parse(document.getElementById('restoreText').value.trim())))}catch(err){alert(`Could not restore backup: ${err.message}`)}}}
  function backupCard(){const m=meta(),since=Math.max(0,completed()-(m.completedAtBackup||0));return `<section class="card stack backup-card"><div><p class="eyebrow">YOUR TRAINING DATA</p><h3>Backup</h3><p class="muted">Keep a copy outside the app. Copy is fastest; Export creates a JSON file when iOS allows it.</p></div><div class="grid-2"><div class="metric"><span class="muted">Last backup</span><strong>${m.lastBackupAt?new Date(m.lastBackupAt).toLocaleDateString():'Never'}</strong></div><div class="metric"><span class="muted">New workouts</span><strong>${since}</strong></div></div>${since>=3||!m.lastBackupAt?`<div class="notice">${!m.lastBackupAt?'Create your first backup now.':`You have ${since} completed workouts since your last backup.`}</div>`:''}<button class="primary" id="copyBackupBtn">Copy backup</button><button class="secondary" id="exportBackupBtn">Export backup file</button><button class="secondary" id="showBackupBtn">Show backup text</button><button class="secondary" id="showRestoreBtn">Restore a backup</button></section>`}
  const oldSettings=settingsView;settingsView=()=>backupCard()+oldSettings().replace('<button class="secondary" id="exportBtn">Export backup</button>','').replace('<button class="secondary" id="importBtn">Import backup</button>','');
  const oldBind=bind;bind=function(view){oldBind(view);if(view==='settings'){const copy=document.getElementById('copyBackupBtn'),exp=document.getElementById('exportBackupBtn'),show=document.getElementById('showBackupBtn'),restore=document.getElementById('showRestoreBtn');if(copy)copy.onclick=copyBackup;if(exp)exp.onclick=exportBackup;if(show)show.onclick=()=>showBackup();if(restore)restore.onclick=showRestore}};
  exportData=exportBackup;
  window.trainingBackupStatus=()=>({lastBackupAt:meta().lastBackupAt||null,newWorkouts:Math.max(0,completed()-(meta().completedAtBackup||0))});
})();
