(() => {
  const META_KEY='hybrid-training-backup-meta-v1';
  const ALLOWED=['startDate','weight','theme','logs','prescriptions','history','runLevels'];
  const meta=()=>{try{return JSON.parse(localStorage.getItem(META_KEY)||'{}')}catch{return {}}};
  const completed=()=>Object.values(state.logs||{}).filter(x=>x?.completed).length;
  const backupPayload=()=>{const data={};ALLOWED.forEach(k=>{if(state[k]!==undefined)data[k]=state[k]});return {format:'hybrid-training-backup',version:2,createdAt:new Date().toISOString(),data}};
  const validObject=v=>v&&typeof v==='object'&&!Array.isArray(v);
  function validate(payload){if(!validObject(payload)||payload.format!=='hybrid-training-backup'||!validObject(payload.data))throw new Error('Not a Hybrid Training backup.');const d=payload.data;if(typeof d.startDate!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(d.startDate))throw new Error('Backup start date is invalid.');if(typeof d.weight!=='number'||!Number.isFinite(d.weight))throw new Error('Backup body weight is invalid.');if(typeof d.theme!=='string')throw new Error('Backup theme is invalid.');['logs','prescriptions','history'].forEach(k=>{if(!validObject(d[k]))throw new Error(`Backup ${k} is invalid.`)});if(d.runLevels!==undefined&&!validObject(d.runLevels))throw new Error('Backup running progression is invalid.');return d}
  function markBackedUp(payload){localStorage.setItem(META_KEY,JSON.stringify({lastBackupAt:payload.createdAt,completedAtBackup:completed()}))}
  function showBackup(){const payload=backupPayload();const text=JSON.stringify(payload);workoutDialog.innerHTML=`<div class="sheet-content"><div class="between row"><div><p class="eyebrow">MANUAL BACKUP</p><h2>Your backup data</h2></div><button class="icon-button" id="closeBackup">×</button></div><div class="notice">This text IS your backup. Press and hold inside the box, choose Select All → Copy, then paste it into an iCloud Note. This does not depend on the clipboard API.</div><textarea id="backupText" readonly style="width:100%;min-height:260px;font-size:12px;line-height:1.35;word-break:break-all">${text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</textarea><button class="primary" id="selectBackup">Select all backup text</button><button class="secondary" id="backupSaved">I saved this backup</button></div>`;workoutDialog.showModal();closeBackup.onclick=()=>workoutDialog.close();selectBackup.onclick=()=>{backupText.focus();backupText.setSelectionRange(0,backupText.value.length)};backupSaved.onclick=()=>{markBackedUp(payload);workoutDialog.close();render('settings')}}
  function restoreData(data){const count=Object.values(data.logs||{}).filter(x=>x?.completed).length;if(!confirm(`Restore this backup?\n\nIt contains ${count} completed workouts.\n\nYour current app data will be replaced.`))return;ALLOWED.forEach(k=>delete state[k]);Object.assign(state,data);save();localStorage.setItem(META_KEY,JSON.stringify({lastBackupAt:new Date().toISOString(),completedAtBackup:count}));location.reload()}
  function showRestore(){workoutDialog.innerHTML=`<div class="sheet-content"><div class="between row"><div><p class="eyebrow">RESTORE</p><h2>Paste backup</h2></div><button class="icon-button" id="closeRestore">×</button></div><p class="muted">Paste the complete backup text from your iCloud Note.</p><textarea id="restoreText" style="width:100%;min-height:220px;font-size:12px" placeholder="Paste backup JSON here"></textarea><button class="primary" id="restoreNow">Validate and restore</button></div>`;workoutDialog.showModal();closeRestore.onclick=()=>workoutDialog.close();restoreNow.onclick=()=>{try{restoreData(validate(JSON.parse(restoreText.value.trim())))}catch(err){alert(`Could not restore backup: ${err.message}`)}}}
  function backupCard(){const m=meta(),since=Math.max(0,completed()-(m.completedAtBackup||0));return `<section class="card stack backup-card"><div><p class="eyebrow">YOUR TRAINING DATA</p><h3>Backup</h3><p class="muted">The safest iPhone method is now completely manual: the app displays the backup text and you save it to iCloud Notes.</p></div><div class="grid-2"><div class="metric"><span class="muted">Last backup</span><strong>${m.lastBackupAt?new Date(m.lastBackupAt).toLocaleDateString():'Never'}</strong></div><div class="metric"><span class="muted">New workouts</span><strong>${since}</strong></div></div>${since>=3||!m.lastBackupAt?`<div class="notice">${!m.lastBackupAt?'Create your first backup now.':`You have ${since} completed workouts since your last backup.`}</div>`:''}<button class="primary" id="showBackupBtn">Show my backup</button><button class="secondary" id="showRestoreBtn">Restore a backup</button></section>`}
  const oldSettings=settingsView;settingsView=()=>backupCard()+oldSettings().replace('<button class="secondary" id="exportBtn">Export backup</button>','').replace('<button class="secondary" id="importBtn">Import backup</button>','');
  const oldBind=bind;bind=function(view){oldBind(view);if(view==='settings'){showBackupBtn.onclick=showBackup;showRestoreBtn.onclick=showRestore}};
  exportData=showBackup;
  window.trainingBackupStatus=()=>({lastBackupAt:meta().lastBackupAt||null,newWorkouts:Math.max(0,completed()-(meta().completedAtBackup||0))});
})();
